import React, { useEffect, useState } from "react";
import { BriefcaseBusiness, CalendarCheck, Check, ExternalLink, FileText, Globe2, Plus, Save, Sparkles, Target, Trash2 } from "lucide-react";
import { C } from "../../theme.js";
import Card from "../../components/Card.jsx";

const initialResume = { name: "", headline: "", summary: "", email: "", location: "", skills: "", experience: "", education: "" };
const resources = {
  JavaScript: ["MDN JavaScript Guide", "Frontend Mentor practice"], React: ["React documentation", "Build a component challenge"], "Node.js": ["Node.js learn path", "REST API exercise"], SQL: ["SQLBolt lessons", "Practice query patterns"], Python: ["Python documentation", "Algorithm practice"], TypeScript: ["TypeScript handbook", "Typed utility exercise"], AWS: ["AWS Skill Builder", "Deploy a small service"], "System Design": ["System Design Primer", "Draw one service architecture"],
};
const opportunities = ["Campus placement office", "Alumni coffee chat", "Local developer meetup", "Open source good-first issue", "Mock interview circle"];

function ResumePreview({ resume }) {
  return <div className="resume-preview"><div className="resume-preview-header"><h2>{resume.name || "Your name"}</h2><p>{resume.headline || "Your target role"}</p><small>{resume.email || "email@example.com"} {resume.location && `· ${resume.location}`}</small></div><section><h3>Profile</h3><p>{resume.summary || "Your professional summary will appear here."}</p></section><section><h3>Skills</h3><p>{resume.skills || "JavaScript · React · SQL"}</p></section><section><h3>Experience</h3><p>{resume.experience || "Add your experience, projects, and measurable outcomes."}</p></section><section><h3>Education</h3><p>{resume.education || "Add your degree or learning program."}</p></section></div>;
}

export default function CareerStudio() {
  const [tab, setTab] = useState("resume");
  const [resume, setResume] = useState(initialResume);
  const [goals, setGoals] = useState([]);
  const [goal, setGoal] = useState("");
  const [portfolio, setPortfolio] = useState([]);
  const [networkNote, setNetworkNote] = useState("");
  const [routine, setRoutine] = useState({ mindset: "", logistics: "", sustainability: "" });
  const [saved, setSaved] = useState(false);
  useEffect(() => { setResume(JSON.parse(localStorage.getItem("pathway-resume") || "null") || initialResume); setGoals(JSON.parse(localStorage.getItem("pathway-goals") || "[]")); setPortfolio(JSON.parse(localStorage.getItem("pathway-portfolio") || "[]")); setRoutine(JSON.parse(localStorage.getItem("pathway-routine") || "null") || routine); }, []);
  const persist = (key, value) => localStorage.setItem(key, JSON.stringify(value));
  const saveResume = () => { persist("pathway-resume", resume); setSaved(true); setTimeout(() => setSaved(false), 1800); };
  const addGoal = (event) => { event.preventDefault(); if (!goal.trim()) return; const next = [...goals, { id: Date.now(), title: goal.trim(), done: false }]; setGoals(next); persist("pathway-goals", next); setGoal(""); };
  const toggleGoal = (id) => { const next = goals.map((item) => item.id === id ? { ...item, done: !item.done } : item); setGoals(next); persist("pathway-goals", next); };
  const uploadPortfolio = (event) => { const files = Array.from(event.target.files || []).map((file) => ({ id: `${file.name}-${file.lastModified}`, name: file.name, size: file.size })); const next = [...portfolio, ...files]; setPortfolio(next); persist("pathway-portfolio", next); };
  const gapSkills = Object.entries(resources).slice(0, 5);
  const updateResume = (key) => (event) => setResume((current) => ({ ...current, [key]: event.target.value }));
  const updateRoutine = (key) => (event) => { const next = { ...routine, [key]: event.target.value }; setRoutine(next); persist("pathway-routine", next); };
  const tabs = [{ id: "resume", label: "Resume studio" }, { id: "goals", label: "Weekly goals" }, { id: "resources", label: "Skill resources" }, { id: "network", label: "Networking hub" }, { id: "routine", label: "Mindset & routine" }];
  return <div className="tool-page"><div className="tool-heading"><div><div className="tool-kicker">Career studio</div><h1>Build your professional edge</h1><p>Shape the story, habits, evidence, and relationships behind your next opportunity.</p></div><BriefcaseBusiness size={32} color={C.green700} /></div>
    <div className="studio-tabs">{tabs.map((item) => <button className={tab === item.id ? "studio-tab active" : "studio-tab"} key={item.id} onClick={() => setTab(item.id)}>{item.label}</button>)}</div>
    {tab === "resume" && <div className="studio-layout"><Card><div className="studio-card-heading"><div><h2>Resume editor</h2><p className="tool-muted">Edit once and watch your professional profile update live.</p></div><button className="secondary-tool-button" onClick={saveResume}><Save size={14} /> {saved ? "Saved" : "Save"}</button></div><div className="resume-form">{[["name", "Full name"], ["headline", "Target headline"], ["email", "Email"], ["location", "Location"]].map(([key, label]) => <label key={key}>{label}<input value={resume[key]} onChange={updateResume(key)} placeholder={label} /></label>)}{[["summary", "Professional summary"], ["skills", "Skills"], ["experience", "Experience and achievements"], ["education", "Education"]].map(([key, label]) => <label key={key}>{label}<textarea rows={key === "summary" ? 4 : 3} value={resume[key]} onChange={updateResume(key)} placeholder={`Write your ${label.toLowerCase()}...`} /></label>)}</div></Card><Card><div className="studio-card-heading"><div><h2>Live preview</h2><p className="tool-muted">A clean, recruiter-ready profile template.</p></div><FileText size={21} color={C.green700} /></div><ResumePreview resume={resume} /></Card></div>}
    {tab === "goals" && <div className="studio-layout"><Card><h2>Weekly goal setter</h2><p className="tool-muted">Choose three small actions you can actually finish this week.</p><form className="inline-form" onSubmit={addGoal}><input value={goal} onChange={(event) => setGoal(event.target.value)} placeholder="e.g. Finish two SQL practice sets" /><button className="secondary-tool-button"><Plus size={14} /> Add goal</button></form>{goals.map((item) => <div className="goal-row" key={item.id}><button className="goal-check" onClick={() => toggleGoal(item.id)}>{item.done && <Check size={14} />}</button><span className={item.done ? "goal-done" : ""}>{item.title}</span><CalendarCheck size={15} color={C.sub} /></div>)}</Card><Card><h2>Reminder rhythm</h2><p className="tool-muted">A weekly review keeps your plan realistic.</p><div className="routine-callout"><Target size={20} color={C.green700} /><div><strong>Sunday planning</strong><p>Pick one skill, one evidence task, and one human connection for the week.</p></div></div><div className="routine-callout"><Check size={20} color={C.green700} /><div><strong>Friday reflection</strong><p>Mark what shipped, what blocked you, and what needs to move forward.</p></div></div></Card></div>}
  {tab === "resources" && <Card><h2>Resources for your skill gaps</h2><p className="tool-muted">Focused material mapped to the skills you are building.</p><div className="resource-grid">{gapSkills.map(([skill, items]) => <div className="resource-card" key={skill}><strong>{skill}</strong>{items.map((item) => <a href={`https://www.google.com/search?q=${encodeURIComponent(item)}`} target="_blank" rel="noreferrer" key={item}>{item} <ExternalLink size={12} /></a>)}</div>)}</div></Card>}
  {tab === "network" && <div className="studio-layout"><Card><h2>Networking hub</h2><p className="tool-muted">Turn opportunity awareness into one human action each week.</p>{opportunities.map((item) => <div className="opportunity-row" key={item}><Globe2 size={17} color={C.green700} /><span>{item}</span><button className="secondary-tool-button" onClick={() => setNetworkNote(`${item} added to this week's plan.`)}>Track</button></div>)}{networkNote && <div className="result-note">{networkNote}</div>}</Card><Card><h2>Conversation starter</h2><p className="tool-muted">I am building toward {resume.headline || "my target role"}. What skill helped you most when you were starting?</p><div className="routine-callout"><Sparkles size={19} color={C.amber} /><div><strong>Awareness prompt</strong><p>Check your university board, alumni groups, meetups, and company events once a week.</p></div></div></Card></div>}
  {tab === "routine" && <div className="studio-layout"><Card><h2>Mindset, logistics, sustainability</h2><p className="tool-muted">Write a routine that protects consistency instead of demanding perfection.</p>{[["mindset", "Mindset reminder", "What will you tell yourself when a session goes badly?"], ["logistics", "Logistics plan", "When and where will you practice, apply, or connect?"], ["sustainability", "Sustainability rule", "What boundary keeps this routine healthy for you?"]].map(([key, label, placeholder]) => <label className="tool-form-label" key={key}>{label}<textarea rows={4} value={routine[key]} onChange={updateRoutine(key)} placeholder={placeholder} /></label>)}</Card><Card><h2>Portfolio uploader</h2><p className="tool-muted">Keep resumes, case studies, certificates, and project files together.</p><label className="upload-zone"><Plus size={20} /><span>Choose files</span><input type="file" multiple onChange={uploadPortfolio} /></label>{portfolio.map((file) => <div className="file-row" key={file.id}><FileText size={16} color={C.green700} /><span>{file.name}</span><Trash2 size={15} color={C.sub} /></div>)}</Card></div>}
  </div>;
}
