const question = (id, prompt, options, answer) => ({ id, prompt, options, answer });
const coding = (id, title, prompt) => ({ id, title, prompt });

export const SKILL_ASSESSMENTS = [
  {
    id: "javascript", skill: "JavaScript", description: "Language fundamentals, async code, and browser behavior.",
    questions: [
      question("js-1", "What does a closure retain?", ["Access to its lexical scope", "A database connection", "Only its return value", "A CSS stylesheet"], 0),
      question("js-2", "Which value represents an intentional absence of an object value?", ["undefined", "null", "NaN", "false"], 1),
      question("js-3", "What does Array.prototype.map return?", ["The original array only", "A new transformed array", "A Promise always", "A number"], 1),
      question("js-4", "What does an async function return?", ["A Promise", "A generator", "A DOM node", "A callback"], 0),
      question("js-5", "Which keyword prevents reassignment of a binding?", ["var", "let", "const", "static"], 2),
      question("js-6", "What is the result of strict equality checking?", ["It compares value and type", "It compares only text", "It converts every value", "It checks object identity only"], 0),
      question("js-7", "Which queue runs Promise callbacks?", ["The microtask queue", "The render queue", "The file queue", "The style queue"], 0),
      question("js-8", "What does destructuring do?", ["Extracts values from arrays or objects", "Encrypts an object", "Creates a database table", "Compiles CSS"], 0),
      question("js-9", "Which method combines array items into one value?", ["reduce", "filter", "slice", "every"], 0),
      question("js-10", "What does JSON.parse do?", ["Converts JSON text into a JavaScript value", "Converts code into CSS", "Sends an HTTP request", "Hashes a password"], 0),
    ],
    coding: [
      coding("js-code-1", "Group duplicate values", "Write a function that returns an object containing the frequency of every value in an array."),
      coding("js-code-2", "Limit concurrent work", "Write an async function that runs an array of async tasks with at most two tasks running at once."),
    ],
  },
  {
    id: "react", skill: "React", description: "Components, state, effects, and predictable rendering.",
    questions: [
      question("react-1", "Which hook stores local component state?", ["useEffect", "useState", "useMemo", "useRef"], 1),
      question("react-2", "Why does a list item need a key?", ["To help React identify it between renders", "To encrypt it", "To style it", "To fetch it"], 0),
      question("react-3", "Props are best described as:", ["Read-only inputs from a parent", "Global database rows", "Private mutable state", "CSS variables"], 0),
      question("react-4", "When does useEffect run by default?", ["After every committed render", "Before the component is parsed", "Only on the server", "Never"], 0),
      question("react-5", "What is a controlled input?", ["Its value is driven by React state", "It cannot receive focus", "It uses only CSS", "It is always disabled"], 0),
      question("react-6", "What does lifting state up mean?", ["Moving shared state to a common parent", "Moving state to the database", "Deleting state", "Using more CSS"], 0),
      question("react-7", "What should a component return?", ["A renderable React element tree", "A SQL query", "A CSS file", "A server socket"], 0),
      question("react-8", "What is a fragment used for?", ["Grouping elements without an extra DOM node", "Loading an image", "Storing state", "Calling an API"], 0),
      question("react-9", "What does memoization help avoid?", ["Unnecessary recalculation or rendering", "All network failures", "Type errors", "Authentication"], 0),
      question("react-10", "Which hook is intended for mutable values that do not trigger renders?", ["useRef", "useState", "useContext", "useId"], 0),
    ],
    coding: [
      coding("react-code-1", "Build a search component", "Create a React search component with a controlled input, a loading state, and a filtered result list."),
      coding("react-code-2", "Reusable pagination", "Create a reusable pagination component that receives page, total pages, and an onChange callback."),
    ],
  },
  {
    id: "node-js", skill: "Node.js", description: "Servers, modules, APIs, and asynchronous I/O.",
    questions: [
      question("node-1", "Which module creates an HTTP server?", ["http", "path", "events", "crypto"], 0),
      question("node-2", "What does npm primarily manage?", ["Packages and project scripts", "Browser cookies", "Database indexes", "CSS layouts"], 0),
      question("node-3", "What does non-blocking I/O allow?", ["Other work while I/O is waiting", "Synchronous disk locking", "Only one request total", "No callbacks"], 0),
      question("node-4", "Which object represents the current module?", ["module", "window", "document", "browser"], 0),
      question("node-5", "What is middleware in an Express app?", ["A function in the request-response chain", "A database table", "A CSS utility", "A browser plugin"], 0),
      question("node-6", "What does process.env contain?", ["Environment variables", "DOM elements", "SQL rows", "React props"], 0),
      question("node-7", "Which status code means a resource was created?", ["200", "201", "301", "404"], 1),
      question("node-8", "What does JSON.stringify do?", ["Converts a value to JSON text", "Parses a URL", "Starts a server", "Encrypts data"], 0),
      question("node-9", "Why should secrets stay out of source code?", ["To prevent accidental exposure", "To improve CSS", "To increase CPU speed", "To create routes"], 0),
      question("node-10", "What does a Promise represent?", ["The eventual result of async work", "A file descriptor only", "A server port", "A stylesheet"], 0),
    ],
    coding: [
      coding("node-code-1", "Create a rate limiter", "Implement Express middleware that limits each client to a fixed number of requests per minute."),
      coding("node-code-2", "Build a paginated endpoint", "Implement an Express GET endpoint that validates page parameters and returns paginated records."),
    ],
  },
  {
    id: "sql", skill: "SQL", description: "Queries, joins, aggregation, and data integrity.",
    questions: [
      question("sql-1", "Which clause filters rows before grouping?", ["ORDER BY", "WHERE", "CREATE", "ALTER"], 1),
      question("sql-2", "Which clause filters groups after aggregation?", ["HAVING", "WHERE", "LIMIT", "VALUES"], 0),
      question("sql-3", "What does an INNER JOIN return?", ["Rows matching on both sides", "Every row from the left", "Only duplicate columns", "Only null rows"], 0),
      question("sql-4", "What does COUNT(*) count?", ["Rows", "Only non-null strings", "Tables", "Indexes"], 0),
      question("sql-5", "What is a primary key?", ["A unique row identifier", "A sorting instruction", "A backup copy", "A view"], 0),
      question("sql-6", "What does an index usually improve?", ["Lookup speed", "Table storage capacity", "Password strength", "Network encryption"], 0),
      question("sql-7", "What does a transaction provide?", ["A unit of work with commit or rollback", "A frontend component", "A search engine", "A CSS rule"], 0),
      question("sql-8", "Which command changes existing rows?", ["UPDATE", "CREATE", "GRANT", "DESCRIBE"], 0),
      question("sql-9", "What does normalization reduce?", ["Unnecessary duplication", "All queries", "User permissions", "Indexes"], 0),
      question("sql-10", "Which keyword removes duplicate result rows?", ["DISTINCT", "UNIQUEIFY", "DEDUP", "SINGLE"], 0),
    ],
    coding: [
      coding("sql-code-1", "Top customers", "Write a query that returns the five customers with the highest total order value in the last 30 days."),
      coding("sql-code-2", "Detect duplicate emails", "Write a query that lists email addresses appearing more than once and their occurrence count."),
    ],
  },
  {
    id: "system-design", skill: "System Design", description: "Scalable services, reliability, storage, and trade-offs.",
    questions: [
      question("design-1", "What is the main purpose of a load balancer?", ["Distribute traffic across servers", "Store passwords", "Compile code", "Create tables"], 0),
      question("design-2", "What does horizontal scaling add?", ["More service instances", "A larger single disk only", "More CSS", "Fewer users"], 0),
      question("design-3", "What is caching used for?", ["Reducing repeated expensive work", "Replacing authentication", "Deleting backups", "Writing CSS"], 0),
      question("design-4", "What does a queue help decouple?", ["Producers and consumers", "HTML and CSS", "Users and passwords", "Tables and columns"], 0),
      question("design-5", "What is eventual consistency?", ["Replicas converge after a delay", "Every read is always latest", "No data is stored", "Only one server exists"], 0),
      question("design-6", "What does a circuit breaker help prevent?", ["Cascading failures", "Duplicate CSS", "Slow compilation", "Bad joins"], 0),
      question("design-7", "What is an idempotent request?", ["Repeating it has the same intended effect", "It always fails", "It has no response", "It changes every row"], 0),
      question("design-8", "Why partition data?", ["To distribute storage and load", "To remove all indexes", "To hide errors", "To avoid APIs"], 0),
      question("design-9", "What does a service-level objective define?", ["A target for service reliability or performance", "A database schema", "A UI color", "A password"], 0),
      question("design-10", "What is a read replica?", ["A copy serving read traffic", "A write-only queue", "A browser cache", "A load balancer rule"], 0),
    ],
    coding: [
      coding("design-code-1", "Design a URL shortener", "Describe the API, data model, key generation, and scaling strategy for a URL-shortening service."),
      coding("design-code-2", "Design a notification service", "Design a service that delivers email and push notifications reliably with retries and deduplication."),
    ],
  },
  {
    id: "python", skill: "Python", description: "Core syntax, data structures, functions, and standard tools.",
    questions: [
      question("python-1", "Which type stores key-value pairs?", ["list", "tuple", "set", "dict"], 3),
      question("python-2", "What does a list comprehension create?", ["A list from an expression and iterable", "A database", "A class only", "A thread"], 0),
      question("python-3", "What does len(value) return?", ["The number of items", "The memory address", "The type name", "The last item"], 0),
      question("python-4", "What does None represent?", ["The absence of a value", "Zero only", "An empty list only", "A syntax error"], 0),
      question("python-5", "Which block handles an exception?", ["except", "catch", "rescue", "handle"], 0),
      question("python-6", "What does a generator yield?", ["Values lazily over iteration", "A database table", "Only strings", "A CSS class"], 0),
      question("python-7", "What is a virtual environment for?", ["Isolating project dependencies", "Increasing monitor resolution", "Hosting images", "Replacing Git"], 0),
      question("python-8", "What does `==` compare?", ["Values", "Variable names only", "Memory size", "File permissions"], 0),
      question("python-9", "Which structure is immutable?", ["tuple", "list", "dict", "set"], 0),
      question("python-10", "What does `with open(...)` help manage?", ["A resource lifecycle", "A React component", "A network route", "A CSS variable"], 0),
    ],
    coding: [
      coding("python-code-1", "Merge intervals", "Write a function that merges all overlapping intervals and returns a sorted list of non-overlapping intervals."),
      coding("python-code-2", "Stream a large file", "Write a generator that yields only matching lines from a large file without loading the whole file into memory."),
    ],
  },
  {
    id: "typescript", skill: "TypeScript", description: "Types, generics, narrowing, and safer JavaScript APIs.",
    questions: [
      question("ts-1", "What does TypeScript add to JavaScript?", ["Static type checking", "A database", "CSS styling", "A web server"], 0),
      question("ts-2", "What is an interface used to describe?", ["The shape of a value", "A running process", "A SQL index", "A browser tab"], 0),
      question("ts-3", "What does a union type allow?", ["One of several possible types", "Only objects", "Only strings", "No values"], 0),
      question("ts-4", "What does a generic preserve?", ["Type relationships across reusable code", "Database rows", "Runtime CSS", "Network sockets"], 0),
      question("ts-5", "What does `unknown` require before use?", ["Type narrowing", "A database", "A JSX file", "A decorator"], 0),
      question("ts-6", "What is an optional property marked with?", ["?", "!", "#", "@"], 0),
      question("ts-7", "What does `readonly` prevent?", ["Assignment after initialization", "Reading a value", "Compilation", "Function calls"], 0),
      question("ts-8", "What is type inference?", ["The compiler deducing a type", "A runtime network call", "A database migration", "A CSS transform"], 0),
      question("ts-9", "What does an enum represent?", ["A named set of related constants", "A server", "A React hook", "A query"], 0),
      question("ts-10", "What does a type guard do?", ["Narrows a value to a safer type", "Deletes a type", "Starts a build", "Formats CSS"], 0),
    ],
    coding: [
      coding("ts-code-1", "Typed groupBy", "Implement a generic groupBy function that groups objects by a selected key while preserving useful TypeScript types."),
      coding("ts-code-2", "Result type", "Define and use a discriminated Result type for a function that can return either data or a typed error."),
    ],
  },
  {
    id: "aws", skill: "AWS", description: "Cloud services, security, networking, and deployment choices.",
    questions: [
      question("aws-1", "Which AWS service stores objects?", ["EC2", "S3", "Lambda", "RDS"], 1),
      question("aws-2", "What is EC2?", ["Virtual servers", "Object storage", "A DNS record", "A queue only"], 0),
      question("aws-3", "What is Lambda suited for?", ["Event-driven serverless functions", "Long-lived desktop apps", "CSS hosting only", "Manual backups only"], 0),
      question("aws-4", "What does IAM control?", ["Identity and permissions", "Image resizing", "SQL joins", "Frontend state"], 0),
      question("aws-5", "What is RDS?", ["Managed relational databases", "A CDN", "A message queue", "A container registry"], 0),
      question("aws-6", "What does CloudFront provide?", ["Content delivery at edge locations", "Database transactions", "User passwords", "Code compilation"], 0),
      question("aws-7", "What is a VPC?", ["An isolated virtual network", "A coding language", "A file format", "A query"], 0),
      question("aws-8", "What is an availability zone?", ["An isolated location within a region", "A user role", "A storage object", "A DNS alias"], 0),
      question("aws-9", "What is the principle of least privilege?", ["Grant only required permissions", "Give every user admin access", "Disable logging", "Share one password"], 0),
      question("aws-10", "What does autoscaling adjust?", ["Resource capacity based on demand", "Database column names", "User roles only", "DNS text"], 0),
    ],
    coding: [
      coding("aws-code-1", "Secure file upload", "Design an S3 upload flow using a presigned URL, validation, private storage, and least-privilege permissions."),
      coding("aws-code-2", "Reliable worker", "Design a Lambda worker that consumes queue messages, retries transient failures, and prevents duplicate processing."),
    ],
  },
];